services:
  traefik:
    image: 'traefik:v2.9.6'
    container_name: 'traefik'
    hostname: traefik
    ports:
      - '80:80'
      - '443:443'
      # for metrics
      - '8082:8082'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/ssl:/ssl

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.rule=Host(`traefik.local.es`)
      - traefik.http.routers.dashboard.service=api@internal

  web1:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.web1.entrypoints=web
      - traefik.http.routers.web1.rule=Host(`web1.local.es`)
      # - traefik.http.routers.web1.tls=true
      # - traefik.http.routers.web1.tls.certresolver=production
    volumes:
      - ./web1:/usr/share/nginx/html

  web2:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.web2.entrypoints=web
      - traefik.http.routers.web2.rule=Host(`web2.local.es`)
    volumes:
      - ./web2:/usr/share/nginx/html
